project:
  type: website
  output-dir: docs
website:
  title: "This is me"
  
  navbar:
    left:
      
      - href: index.qmd
        text: Home
      - about.qmd      
      - href: present.qmd
        text: Current
      - href: blog.qmd
        text: Blog
      
  sidebar:
    style: "docked"
    logo: "./images/user_image.png"
    search: true
    collapse-level: 2
    contents:
      - icon: github
        text: Github
        url: https://github.com/AkhilaSunesh
      - icon: instagram
        text: Instagram
        url: https://www.instagram.com/akhila_sunesh/
      - icon: Email
      - text: "Email"
        url: mailto:akhilasunesh@gmail.com
format:
  html:
    theme: minty
    css: styles.css
    toc: true
  


